name: First Workflow
on: 
  push:
    branches:
      - main
      - master
      - develop
      - 'release/**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build phase
        run: echo " My name is ${{vars.MY_NAME}}"
