name: First Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build phase
        run: echo"first build"
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Test Phase
        run : echo " run test cases"
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy to prod
        run :  echo "deploying to productions"
      
    
