name: First Workflow
on: 
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
    branches:
      - main
      - feature/pr-demo
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build phase
        run: echo "we are testing build"